steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - testCd
      - --source=.
      - --entry-point
      - TestRequest
      - --runtime
      - go113
      - --trigger-http
    env: ['GOPATH=/gopath']
    dir: './'